Pre-merge master into bigtable-client-2.x (#2334)
* Update dependency com.fasterxml.jackson.core:jackson-databind to v2.10.0 (#2243)

* Fix Travis build status and landing page [skip ci] (#2260)

Update the name of the repo to match current state, which fixes both issues

* Fix for checknig Bad tableName for H2 IT test case (#2269)

* chore: drop signatures from shaded jars (#2273)

* fix: update url in pom file (#2279)

This change update the repository url in `<scm>` and `<issueManagement>`
section

* chore(deps): update dependency org.apache.maven.plugins:maven-jar-plugin to v3.2.0 (#2264)

* Update dependency com.fasterxml.jackson.core:jackson-databind to v2.10.1 (#2268)

* Fix: includes fixes for the gap between HBase and this client (#2267)

This change includes fixes for the below methods:

- Admin#listTableNames(Pattern)

- Admin#getTableDescriptorsByTableName(List)(It is called by below operations)
  - Admin#getTableDescriptors(List)
  - Admin#listTables(Pattern)
  - Admin#enableTables(Pattern)
  - Admin#disableTables(Pattern)
  - Admin#deleteTables(Pattern)

- Admin#isTableDisabled(TableName)
  - Admin#isTableEnabled(TableName)

* chore(deps): update dependency org.apache.maven.plugins:maven-source-plugin to v3.2.0 (#2265)

* Update dependency org.mockito:mockito-core to v3.1.0 (#2244)

* Update hamcrest.version to v2.2 (#2254)

* Update dependency com.google.auto.value:auto-value to v1.7 (#2251)

* Update dependency org.slf4j:slf4j-api to v1.7.29 (#2262)

* Revert "Fix: includes fixes for the gap between HBase and this client (#2267)" (#2282)

This reverts commit 51f0617aa8c9865b066e9bfaa25f053c7f0ad3d4.

* chore(deps): force upgrade grpc to 1.25.0 (#2272)

* chore(deps): force upgrade grpc to 1.25.0

* compilation fixes

* chore(deps): update renovate config (#2292)

* chore(deps): update renovate config

* chore(deps): update renovate config

* docs: Updated readme to redirect user to veneer client (#2288)

This change adds a note in `BigtableOption.java`, `BigtableSession.java`
and README.md to redirect people to google-cloud-bigtable client.

* [Part-1] Adding Integration test cases for Table API (#2266)

* Adding fixes for HBase Table API

* fix: verification for Batch.Callback never being called in case of Empty list

* test: updated batch/put methods with more scenarios

Addressing feedback comments to include more tests scenarios for null
and empty test cases.

* build: add kokoro configs for presubmit tests (#2295)

* build: add kokoro configs for presubmit tests

* rename IT tests

* change back IT tests and config

* remove java 7 config

* build: fix unit test kokoro builds (#2298)

* build: fix IT tests (#2301)

* build: fix IT tests

* build: fix IT tests

* build: fix IT tests

* build: fix IT tests

* build: add in more IT tests (#2302)

* build: add in more IT tests

* add comment

* test: Fix for Gaps b/w HBase and Bigtable Admin API (#2285)

* test: updating gaps for Admin operations

This introduces a new operation Admin.getTableDescriptorIgnoreFailure, which returns TableDescriptor[].

This closes gap between below methods:
- listTables()
- deleteTables()
- enableTables()
- disableTables()
- isTableEnabled()
- isTableDisabled()
- getTableDescriptors()
- getTableDescriptorsByTableName()

* test: add exception type check for admin IT tests

This commit contains exception type check for an extra layer of test. Also removed left out `printstacktrace()`.

* test(docs): updated code comment and handled exception

Update exception handling in
`AbstractBigtableAdmin#getTableDescriptorIgnoreFailure` to only suppress
TableNotFound and FailedPrecondition exception. Also, updated code
comment for the same.

* fix: fixed race condition in lisTables() and tests update

This change updates listTables() to fix the race condition, which could
have occurred when user sends ".*" pattern. Also removed unnecessary
try-catch blocks from IT test cases.

* test: updates snapshot operation with sanitary checks (#2289)

* test: updates snapshot operation with sanitary checks

This change includes sanitary checks to Snapshot operation.

## What is the problem:
If an empty string is being passed on to snapshot operations(#snapshotTable, #listSnapshot) then it fails with `Unimplemented method found` exception message.
```
com.google.bigtable.repackaged.com.google.common.util.concurrent.UncheckedExecutionException: com.google.bigtable.repackaged.io.grpc.StatusRuntimeException: UNIMPLEMENTED: Method not found.
```

## Impact of this change:
Now snapshot operations would not fail with `""` anymore. Also, These methods will behave same as HBase API when passing empty string or `null`.

Towards #2253

* test: add exception type check for admin IT tests

This commit contains exception type check for better verification.

* test: removed unnecessary try catch blocks from Snapshot test cases

* test: removed try/catch and updated explanation for HBase behaviour

* chore: Prepare to cleanup channel management (#2304)

* chore: Prepare to cleanup channel management

This PR doesn't actually change functionality, it simply groups all of the channel creation related method together.
Follow up commits will actually modify the functions

* typo

* chore: cleanup connection initialization (#2303)

* chore: Prepare to cleanup channel management

This PR doesn't actually change functionality, it simply groups all of the channel creation related method together.
Follow up commits will actually modify the functions

* chore: clean up channel creation

* Deprecate all of the like named channel creation methods
* Update channel pool cache to only store the raw grpc channel
* Update channel pool cache to be keyed by endpoint
* Centralize interceptor creation

* typo

* format

* fix test

* remove stray comment

* empty commit

* deps: fix dependency build (#2305)

* deps: fix dependency build

* deps: fix dependency build

* deps: fix dependency build

* deps: fix dependency build

* clean up version numbers

* feedback 1

* feedback 2

* build: fix IT tests

* fix tests

* fix tests

* fix tests

* fix tests

* alphabetize/regroup dependencies

* feedback 3

* feedback 4

* feedback 5

* feedback 6

* feedback 7

* deps: fix hbaseLocalMiniClusterTestH2 tests (#2308)

* Fix hbaseLocalMiniClusterTestH2 tests

* Fix hbaseLocalMiniClusterTestH2 tests

* rename

* more fixes

* chore: fix renovate config (#2315)

* deps: update dependency io.grpc:grpc-bom to v1.26.0

* chore: clean up pom (#2327)

* chore: clean up pom

* revert grpc version bump

* chore(deps): group core dependencies

* remove grpc overrides

Co-authored-by: Renovate Bot <renovatebot@gmail.com>
Co-authored-by: Misha Brukman <mbrukman@google.com>
Co-authored-by: Rahul Kesharwani <42969463+rahulKQL@users.noreply.github.com>
Co-authored-by: kolea2 <45548808+kolea2@users.noreply.github.com>
Co-authored-by: Jeff Ching <chingor@google.com>