Updating GCJ dependency with latest GCJ version (#2181)
* Updating GCJ dependency with latest GCJ version

After updating to `google-cloud-java:0.97.0`, I started to see ClassNotFoundException while creating GCJ connection:
```java
java.lang.ClassNotFoundException: io.grpc.alts.ComputeEngineChannelBuilder
```

For this, we require `grpc-alts` which is transitively coming from `gax-grpc`
```sh
[INFO] |  +- com.google.api:gax-grpc:jar:1.46.1:compile
[INFO] |  |  +- com.google.api:gax:jar:1.46.1:compile
[INFO] |  |  +- org.threeten:threetenbp:jar:1.3.3:compile
[INFO] |  |  \- io.grpc:grpc-alts:jar:1.21.0:compile
[INFO] |  |     +- io.grpc:grpc-grpclb:jar:1.21.0:compile
[INFO] |  |     \- org.apache.commons:commons-lang3:jar:3.5:compile
```

To fix this issue, I've excluded the only other grpc jar(i.e `grpc-grpclb`) from this instead of excluding all grpc jars. I hope this should not create any unknown dependency problem for `bigtable-core`.

* Removed unneeded exclusions tag

Confirm with running Integration test for HBase1 & HBase2