deps: update dependency com.google.errorprone:error_prone_annotations to v2.10.0 (#3330)
[![WhiteSource Renovate](https://app.renovatebot.com/images/banner.svg)](https://renovatebot.com)

This PR contains the following updates:

| Package | Change | Age | Adoption | Passing | Confidence |
|---|---|---|---|---|---|
| [com.google.errorprone:error_prone_annotations](https://errorprone.info) ([source](https://togithub.com/google/error-prone)) | `2.4.0` -> `2.10.0` | [![age](https://badges.renovateapi.com/packages/maven/com.google.errorprone:error_prone_annotations/2.10.0/age-slim)](https://docs.renovatebot.com/merge-confidence/) | [![adoption](https://badges.renovateapi.com/packages/maven/com.google.errorprone:error_prone_annotations/2.10.0/adoption-slim)](https://docs.renovatebot.com/merge-confidence/) | [![passing](https://badges.renovateapi.com/packages/maven/com.google.errorprone:error_prone_annotations/2.10.0/compatibility-slim/2.4.0)](https://docs.renovatebot.com/merge-confidence/) | [![confidence](https://badges.renovateapi.com/packages/maven/com.google.errorprone:error_prone_annotations/2.10.0/confidence-slim/2.4.0)](https://docs.renovatebot.com/merge-confidence/) |

---

### Release Notes

<details>
<summary>google/error-prone</summary>

### [`v2.10.0`](https://togithub.com/google/error-prone/releases/v2.10.0)

[Compare Source](https://togithub.com/google/error-prone/compare/v2.9.0...v2.10.0)

New checks

-   [`AlwaysThrows`](http://errorprone.info/bugpattern/AlwaysThrows)
-   [`StackTraceElementGetClass`](http://errorprone.info/bugpattern/StackTraceElementGetClass)
-   [`BareDotMetacharacter`](http://errorprone.info/bugpattern/BareDotMetacharacter)
-   [`DistinctVarargsChecker`](http://errorprone.info/bugpattern/DistinctVarargsChecker)
-   [`MalformedInlineTag`](http://errorprone.info/bugpattern/MalformedInlineTag)
-   [`MemoizeConstantVisitorStateLookups`](http://errorprone.info/bugpattern/MemoizeConstantVisitorStateLookups)
-   [`UnicodeEscape`](http://errorprone.info/bugpattern/UnicodeEscape)
-   [`FieldMissingNullable`](http://errorprone.info/bugpattern/FieldMissingNullable)
-   [`Java8ApiChecker`](http://errorprone.info/bugpattern/Java8ApiChecker)
-   [`ParameterMissingNullable`](http://errorprone.info/bugpattern/ParameterMissingNullable)
-   [`TooManyParameters`](http://errorprone.info/bugpattern/TooManyParameters)
-   [`TryWithResourcesVariable`](http://errorprone.info/bugpattern/TryWithResourcesVariable)
-   [`UnnecessaryFinal`](http://errorprone.info/bugpattern/UnnecessaryFinal)
-   [`VoidMissingNullable`](http://errorprone.info/bugpattern/VoidMissingNullable)

Fixed issues: [#&#8203;2616](https://togithub.com/google/error-prone/issues/2616), [#&#8203;2629](https://togithub.com/google/error-prone/issues/2629)

**Full Changelog**: https://github.com/google/error-prone/compare/v2.9.0...v2.10.0

### [`v2.9.0`](https://togithub.com/google/error-prone/releases/v2.9.0)

[Compare Source](https://togithub.com/google/error-prone/compare/v2.8.1...v2.9.0)

Release Error Prone 2.9.0

New checks:

-   DeprecatedVariable
-   PublicApiNamedStreamShouldReturnStream

Fixes [#&#8203;2124](https://togithub.com/google/error-prone/issues/2124), [#&#8203;2371](https://togithub.com/google/error-prone/issues/2371), [#&#8203;2393](https://togithub.com/google/error-prone/issues/2393), [#&#8203;2470](https://togithub.com/google/error-prone/issues/2470)

### [`v2.8.1`](https://togithub.com/google/error-prone/releases/v2.8.1)

[Compare Source](https://togithub.com/google/error-prone/compare/v2.8.0...v2.8.1)

This release adds a new check ([LoopOverCharArray](https://errorprone.info/bugpattern/LoopOverCharArray)), and a handful of other small improvements (https://github.com/google/error-prone/compare/v2.8.0...v2.8.1).

### [`v2.8.0`](https://togithub.com/google/error-prone/releases/v2.8.0)

[Compare Source](https://togithub.com/google/error-prone/compare/v2.7.1...v2.8.0)

New Checks:

-   [JUnit4TestsNotRunWithinEnclosed](https://errorprone.info/bugpattern/JUnit4TestsNotRunWithinEnclosed)
-   [OptionalOfRedundantMethod](https://errorprone.info/bugpattern/OptionalOfRedundantMethod)
-   [UnnecessaryAssignment](https://errorprone.info/bugpattern/UnnecessaryAssignment)
-   [UnrecognisedJavadocTag](https://errorprone.info/bugpattern/UnrecognisedJavadocTag)
-   [AnnotationMirrorToString](https://errorprone.info/bugpattern/AnnotationMirrorToString)
-   [AnnotationValueToString](https://errorprone.info/bugpattern/AnnotationValueToString)
-   [EqualsMissingNullable](https://errorprone.info/bugpattern/EqualsMissingNullable)
-   [ReturnMissingNullable](https://errorprone.info/bugpattern/ReturnMissingNullable)

Fixes [#&#8203;1652](https://togithub.com/google/error-prone/issues/1652), [#&#8203;2122](https://togithub.com/google/error-prone/issues/2122), [#&#8203;2122](https://togithub.com/google/error-prone/issues/2122), [#&#8203;2366](https://togithub.com/google/error-prone/issues/2366), [#&#8203;2404](https://togithub.com/google/error-prone/issues/2404), [#&#8203;2411](https://togithub.com/google/error-prone/issues/2411)

### [`v2.7.1`](https://togithub.com/google/error-prone/releases/v2.7.1)

[Compare Source](https://togithub.com/google/error-prone/compare/v2.7.0...v2.7.1)

Everything in [Error Prone 2.7.0](https://togithub.com/google/error-prone/releases/tag/v2.7.0), plus an [additional fix for JDK 17](https://togithub.com/google/error-prone/commit/ff07935205757a2eb8b6ef52af1751948752b6ab).

### [`v2.7.0`](https://togithub.com/google/error-prone/releases/v2.7.0)

[Compare Source](https://togithub.com/google/error-prone/compare/v2.6.0...v2.7.0)

Changes

-   Initial support for running on JDK 17 EA builds. Supports for Java 17 languages features is incomplete; [bug reports](https://togithub.com/google/error-prone/issues) for issues with Java 17 are welcome.
-   `@InlineMe` is a deprecation mechanism that allows automated tools to cleanup existing callers: http://errorprone.info/docs/inlineme

New checks:

-   [EqualsNull](http://errorprone.info/bugpattern/EqualsNull)
-   [MissingBraces](http://errorprone.info/bugpattern/MissingBraces)
-   [NullablePrimitiveArray](http://errorprone.info/bugpattern/NullablePrimitiveArray)
-   [OptionalMapUnusedValue](http://errorprone.info/bugpattern/OptionalMapUnusedValue)
-   [TestParametersNotInitialized](http://errorprone.info/bugpattern/TestParametersNotInitialized)

Closed issues: [#&#8203;2257](https://togithub.com/google/error-prone/issues/2257), [#&#8203;2260](https://togithub.com/google/error-prone/issues/2260), [#&#8203;2282](https://togithub.com/google/error-prone/issues/2282), [#&#8203;2301](https://togithub.com/google/error-prone/issues/2301), [#&#8203;2322](https://togithub.com/google/error-prone/issues/2322), [#&#8203;2323](https://togithub.com/google/error-prone/issues/2323), [#&#8203;2324](https://togithub.com/google/error-prone/issues/2324)

### [`v2.6.0`](https://togithub.com/google/error-prone/releases/v2.6.0)

[Compare Source](https://togithub.com/google/error-prone/compare/v2.5.1...v2.6.0)

Checkers Added:

-   [CharacterGetNumericValue](http://errorprone.info/bugpattern/CharacterGetNumericValue)
-   [ErroneousThreadPoolConstructorChecker](http://errorprone.info/bugpattern/ErroneousThreadPoolConstructorChecker)
-   [FloggerArgumentToString](http://errorprone.info/bugpattern/FloggerArgumentToString)
-   [FloggerStringConcatenation](http://errorprone.info/bugpattern/FloggerStringConcatenation)
-   [ProtoBuilderReturnValueIgnored](http://errorprone.info/bugpattern/ProtoBuilderReturnValueIgnored)
-   [RethrowReflectiveOperationExceptionAsLinkageError](http://errorprone.info/bugpattern/RethrowReflectiveOperationExceptionAsLinkageError)
-   [SystemOut](http://errorprone.info/bugpattern/SystemOut)
-   [UnnecessaryAnonymousClass](http://errorprone.info/bugpattern/UnnecessaryAnonymousClass)

Issues Closed:

-   RFE: configurable DoNotCall/RestrictedApi/JdkObsolete/DefaultCharset/JavaTimeDefaultTimeZone check ([#&#8203;1211](https://togithub.com/google/error-prone/issues/1211))
-   Add SystemOut checker ([#&#8203;1534](https://togithub.com/google/error-prone/issues/1534))
-   WellKnownMutability: add java.awt.Color ([#&#8203;1682](https://togithub.com/google/error-prone/issues/1682))
-   IdentityHashMapUsage warnings differ from its documentation ([#&#8203;2095](https://togithub.com/google/error-prone/issues/2095))
-   UnusedMethod no longer works ([#&#8203;2215](https://togithub.com/google/error-prone/issues/2215))
-   Document naming convention for UnusedMethod ([#&#8203;2223](https://togithub.com/google/error-prone/issues/2223))

### [`v2.5.1`](https://togithub.com/google/error-prone/releases/v2.5.1)

[Compare Source](https://togithub.com/google/error-prone/compare/v2.5.0...v2.5.1)

Changes

NoSuchMethodError: 'com.sun.tools.javac.util.List com.sun.tools.javac.code.Symbol$TypeSymbol.getEnclosedElements

-   Fixed `NoSuchMethodError` crash in `HidingField` ([#&#8203;2092](https://togithub.com/google/error-prone/issues/2092))
-   Fixed `NoSuchElementException` crash in `RestrictedApiChecker` ([#&#8203;2099](https://togithub.com/google/error-prone/issues/2099))
-   False positive in `DifferentNameButSame` ([#&#8203;2094](https://togithub.com/google/error-prone/issues/2094))
-   False positive in `UnnecessaryOptionalGet` ([#&#8203;2101](https://togithub.com/google/error-prone/issues/2101))
-   False positive in `UnnecessaryMethodReference` ([#&#8203;2102](https://togithub.com/google/error-prone/issues/2102))
-   Fixed a regression in JDK 16-EA support ([#&#8203;2105](https://togithub.com/google/error-prone/issues/2105))

### [`v2.5.0`](https://togithub.com/google/error-prone/releases/v2.5.0)

[Compare Source](https://togithub.com/google/error-prone/compare/v2.4.0...v2.5.0)

New checks:

-   [BanSerializableRead](http://errorprone.info/bugpattern/BanSerializableRead)
-   [CatchingUnchecked](http://errorprone.info/bugpattern/CatchingUnchecked)
-   [ComputeIfAbsentAmbiguousReference](http://errorprone.info/bugpattern/ComputeIfAbsentAmbiguousReference)
-   [DangerousLiteralNull](http://errorprone.info/bugpattern/DangerousLiteralNull)
-   [DateChecker](http://errorprone.info/bugpattern/DateChecker)
-   [DifferentNameButSame](http://errorprone.info/bugpattern/DifferentNameButSame)
-   [DoNotCallSuggester](http://errorprone.info/bugpattern/DoNotCallSuggester)
-   [DoNotClaimAnnotations](http://errorprone.info/bugpattern/DoNotClaimAnnotations)
-   [DoNotMockAutoValue](http://errorprone.info/bugpattern/DoNotMockAutoValue)
-   [FloggerFormatString](http://errorprone.info/bugpattern/FloggerFormatString)
-   [FloggerLogVarargs](http://errorprone.info/bugpattern/FloggerLogVarargs)
-   [FloggerLogWithCause](http://errorprone.info/bugpattern/FloggerLogWithCause)
-   [FloggerMessageFormat](http://errorprone.info/bugpattern/FloggerMessageFormat)
-   [FloggerPassedAround](http://errorprone.info/bugpattern/FloggerPassedAround)
-   [FloggerRedundantIsEnabled](http://errorprone.info/bugpattern/FloggerRedundantIsEnabled)
-   [FloggerRequiredModifiers](http://errorprone.info/bugpattern/FloggerRequiredModifiers)
-   [FloggerSplitLogStatement](http://errorprone.info/bugpattern/FloggerSplitLogStatement)
-   [FloggerWithCause](http://errorprone.info/bugpattern/FloggerWithCause)
-   [FloggerWithoutCause](http://errorprone.info/bugpattern/FloggerWithoutCause)
-   [HashCodeToString](http://errorprone.info/bugpattern/HashCodeToString)
-   [IdentityHashMapUsage](http://errorprone.info/bugpattern/IdentityHashMapUsage)
-   [ImmutableMemberCollection](http://errorprone.info/bugpattern/ImmutableMemberCollection)
-   [ImmutableSetForContains](http://errorprone.info/bugpattern/ImmutableSetForContains)
-   [InitializeInline](http://errorprone.info/bugpattern/InitializeInline)
-   [InvalidThrowsLink](http://errorprone.info/bugpattern/InvalidThrowsLink)
-   [IsInstanceIncompatibleType](http://errorprone.info/bugpattern/IsInstanceIncompatibleType)
-   [JavaUtilDate](http://errorprone.info/bugpattern/JavaUtilDate)
-   [JodaConstructors](http://errorprone.info/bugpattern/JodaConstructors)
-   [JodaDateTimeConstants](http://errorprone.info/bugpattern/JodaDateTimeConstants)
-   [LongFloatConversion](http://errorprone.info/bugpattern/LongFloatConversion)
-   [MemberName](http://errorprone.info/bugpattern/MemberName)
-   [MisplacedScopeAnnotations](http://errorprone.info/bugpattern/MisplacedScopeAnnotations)
-   [ObjectEqualsForPrimitives](http://errorprone.info/bugpattern/ObjectEqualsForPrimitives)
-   [OptionalMapUnusedValue](http://errorprone.info/bugpattern/OptionalMapUnusedValue)
-   [ReturnsNullCollection](http://errorprone.info/bugpattern/ReturnsNullCollection)
-   [StaticMockMember](http://errorprone.info/bugpattern/StaticMockMember)
-   [StreamToIterable](http://errorprone.info/bugpattern/StreamToIterable)
-   [SymbolToString](http://errorprone.info/bugpattern/SymbolToString)
-   [TypeToString](http://errorprone.info/bugpattern/TypeToString)
-   [UnnecessarilyVisible](http://errorprone.info/bugpattern/UnnecessarilyVisible)
-   [UnnecessaryMethodReference](http://errorprone.info/bugpattern/UnnecessaryMethodReference)
-   [UnnecessaryOptionalGet](http://errorprone.info/bugpattern/UnnecessaryOptionalGet)
-   [UnsafeLocaleUsage](http://errorprone.info/bugpattern/UnsafeLocaleUsage)
-   [UseEnumSwitch](http://errorprone.info/bugpattern/UseEnumSwitch)
-   [UseTimeInScope](http://errorprone.info/bugpattern/UseTimeInScope)
-   [WrongOneof](http://errorprone.info/bugpattern/WrongOneof)
-   [ZoneIdOfZ](http://errorprone.info/bugpattern/ZoneIdOfZ)

Fixed issues: [#&#8203;1044](https://togithub.com/google/error-prone/issues/1044) [#&#8203;1177](https://togithub.com/google/error-prone/issues/1177) [#&#8203;1275](https://togithub.com/google/error-prone/issues/1275) [#&#8203;1322](https://togithub.com/google/error-prone/issues/1322) [#&#8203;1326](https://togithub.com/google/error-prone/issues/1326) [#&#8203;1503](https://togithub.com/google/error-prone/issues/1503) [#&#8203;1529](https://togithub.com/google/error-prone/issues/1529) [#&#8203;1563](https://togithub.com/google/error-prone/issues/1563) [#&#8203;1645](https://togithub.com/google/error-prone/issues/1645) [#&#8203;1650](https://togithub.com/google/error-prone/issues/1650) [#&#8203;1652](https://togithub.com/google/error-prone/issues/1652) [#&#8203;1653](https://togithub.com/google/error-prone/issues/1653) [#&#8203;1655](https://togithub.com/google/error-prone/issues/1655) [#&#8203;1665](https://togithub.com/google/error-prone/issues/1665) [#&#8203;1670](https://togithub.com/google/error-prone/issues/1670) [#&#8203;1672](https://togithub.com/google/error-prone/issues/1672) [#&#8203;1694](https://togithub.com/google/error-prone/issues/1694) [#&#8203;1699](https://togithub.com/google/error-prone/issues/1699) [#&#8203;1705](https://togithub.com/google/error-prone/issues/1705) [#&#8203;1767](https://togithub.com/google/error-prone/issues/1767) [#&#8203;1788](https://togithub.com/google/error-prone/issues/1788) [#&#8203;1809](https://togithub.com/google/error-prone/issues/1809) [#&#8203;1849](https://togithub.com/google/error-prone/issues/1849) [#&#8203;1873](https://togithub.com/google/error-prone/issues/1873) [#&#8203;1916](https://togithub.com/google/error-prone/issues/1916) [#&#8203;1981](https://togithub.com/google/error-prone/issues/1981) [#&#8203;1982](https://togithub.com/google/error-prone/issues/1982) [#&#8203;1986](https://togithub.com/google/error-prone/issues/1986) [#&#8203;1987](https://togithub.com/google/error-prone/issues/1987) [#&#8203;2009](https://togithub.com/google/error-prone/issues/2009) [#&#8203;2026](https://togithub.com/google/error-prone/issues/2026) [#&#8203;2029](https://togithub.com/google/error-prone/issues/2029) [#&#8203;2059](https://togithub.com/google/error-prone/issues/2059) [#&#8203;2064](https://togithub.com/google/error-prone/issues/2064)

</details>

---

### Configuration

📅 **Schedule**: At any time (no schedule defined).

🚦 **Automerge**: Disabled by config. Please merge this manually once you are satisfied.

♻ **Rebasing**: Whenever PR becomes conflicted, or you tick the rebase/retry checkbox.

🔕 **Ignore**: Close this PR and you won't be reminded about this update again.

---

 - [ ] <!-- rebase-check -->If you want to rebase/retry this PR, click this checkbox.

---

This PR has been generated by [WhiteSource Renovate](https://renovate.whitesourcesoftware.com). View repository job log [here](https://app.renovatebot.com/dashboard#github/googleapis/java-bigtable-hbase).